# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 443)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.CameraButton.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.CameraButton.setObjectName("CameraButton")
        self.SaveImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImageButton.setGeometry(QtCore.QRect(10, 100, 141, 31))
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.StopViewButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopViewButton.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.StopViewButton.setObjectName("StopViewButton")
        self.CameraLabel = QtWidgets.QGroupBox(self.centralwidget)
        self.CameraLabel.setGeometry(QtCore.QRect(190, 20, 481, 341))
        self.CameraLabel.setObjectName("CameraLabel")
        self.CameraWindow = QtWidgets.QLabel(self.CameraLabel)
        self.CameraWindow.setGeometry(QtCore.QRect(0, 20, 481, 321))
        self.CameraWindow.setText("")
        self.CameraWindow.setObjectName("CameraWindow")
        self.LeftEyeWindow = QtWidgets.QLabel(self.centralwidget)
        self.LeftEyeWindow.setGeometry(QtCore.QRect(700, 40, 111, 111))
        self.LeftEyeWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.LeftEyeWindow.setText("")
        self.LeftEyeWindow.setObjectName("LeftEyeWindow")
        self.RightEyeWindow = QtWidgets.QLabel(self.centralwidget)
        self.RightEyeWindow.setGeometry(QtCore.QRect(870, 40, 111, 111))
        self.RightEyeWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.RightEyeWindow.setText("")
        self.RightEyeWindow.setObjectName("RightEyeWindow")
        self.LeftEyeLabel = QtWidgets.QLabel(self.centralwidget)
        self.LeftEyeLabel.setGeometry(QtCore.QRect(730, 20, 51, 16))
        self.LeftEyeLabel.setObjectName("LeftEyeLabel")
        self.RightEyeLabel = QtWidgets.QLabel(self.centralwidget)
        self.RightEyeLabel.setGeometry(QtCore.QRect(900, 20, 61, 16))
        self.RightEyeLabel.setObjectName("RightEyeLabel")
        self.ThresholdSlider = QtWidgets.QSlider(self.centralwidget)
        self.ThresholdSlider.setGeometry(QtCore.QRect(190, 370, 481, 22))
        self.ThresholdSlider.setMaximum(255)
        self.ThresholdSlider.setProperty("value", 0)
        self.ThresholdSlider.setSliderPosition(0)
        self.ThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ThresholdSlider.setObjectName("ThresholdSlider")
        self.ThresholdLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThresholdLabel.setGeometry(QtCore.QRect(130, 370, 51, 21))
        self.ThresholdLabel.setObjectName("ThresholdLabel")
        self.ThresholdValue = QtWidgets.QSpinBox(self.centralwidget)
        self.ThresholdValue.setGeometry(QtCore.QRect(680, 370, 61, 22))
        self.ThresholdValue.setMaximum(255)
        self.ThresholdValue.setObjectName("ThresholdValue")
        self.leftCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.leftCheckBox.setGeometry(QtCore.QRect(730, 160, 61, 17))
        self.leftCheckBox.setObjectName("leftCheckBox")
        self.rightCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rightCheckBox.setGeometry(QtCore.QRect(900, 160, 61, 17))
        self.rightCheckBox.setObjectName("rightCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraButton.setText(_translate("MainWindow", "Show Camera"))
        self.SaveImageButton.setText(_translate("MainWindow", "Save Image"))
        self.StopViewButton.setText(_translate("MainWindow", "Stop Viewing"))
        self.CameraLabel.setTitle(_translate("MainWindow", "Not Active"))
        self.LeftEyeLabel.setText(_translate("MainWindow", "Left Eye"))
        self.RightEyeLabel.setText(_translate("MainWindow", "Right Eye"))
        self.ThresholdLabel.setText(_translate("MainWindow", "Threshold"))
        self.leftCheckBox.setText(_translate("MainWindow", "Track"))
        self.rightCheckBox.setText(_translate("MainWindow", "Track"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze "))
